name: "🐞 Chaos Report"
description: "Found a bug in the world of ChaosWeb? Let us know if it's more than just intentional chaos!"
title: "CHAOS REPORT:"
labels: ["chaos", "bug"]
body:
  - type: checkboxes
    attributes:
      label: "Is there an actual issue here?"
      description: "Please check if what you're experiencing is an actual bug or just a part of the chaotic experience."
      options:
        - label: "I have verified this isn't part of ChaosWeb's intentional disorder"
          required: true
  - type: textarea
    attributes:
      label: "Describe the unexpected!"
      description: "A brief description of what went wrong, and why you think it's a real bug and not just more chaos."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Confirm"
      options:
        - label: "I understand ChaosWeb is intentionally designed to be messy"
          required: true
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I found a genuine bug amidst the chaos"
          required: true
        - label: "I'm enjoying the mess!"
          required: true
        - label: "I'm GSSOC'24 Extd registered Contributor"
        # - label: "I'm Hacktoberfest registered Contributor"

