name: "📚 Chaos Documentation Update"
description: "Spotted a gap in our chaotic documentation or have a way to make it even more unpredictable? Let's hear it!"
title: "Documentation Chaos:"
labels: ["documentation", "chaos"]
body:
    - type: textarea
      attributes:
          label: "Describe the Documentation Update"
          description: "Explain the update or improvement you'd like to add to our documentation. How will it embrace the chaos?"
      validations:
          required: true
    - type: textarea
      attributes:
          label: "Add References or Examples"
          description: "Got any screenshots, sketches, or examples? Visual aids help us navigate the chaos better."
      validations:
          required: false
    - type: checkboxes
      attributes:
          label: "Confirm"
          options:
              - label: "I understand that my update will add to the chaos and I'm okay with it"
                required: true
              - label: "I agree to follow this project's Code of Conduct"
                required: true
              - label: "I want to work on this documentation update"
              - label: "I'm GSSOC'24 Extd registered Contributor"
              # - label: "I'm Hacktoberfest registered Contributor"
