name: "✨ Chaos Feature Suggestion"
description: "Got an idea to make ChaosWeb even more chaotic? Share your twisted vision with us!"
title: "Chaotic Feat:"
labels: ["enhancement", "chaos"]
body:
  - type: textarea
    attributes:
      label: "Describe your chaotic idea"
      description: "Tell us how you'd like to make ChaosWeb even messier or more unpredictable."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add Screenshots or Sketches"
      description: "Visual aids are welcome in this chaotic world! Add any screenshots or sketches to help explain your idea."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Confirm"
      options:
        - label: "I understand that my idea will add to the chaos and I'm okay with it"
          required: true
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I want to work on this feature"
        - label: "I'm GSSOC'24 Extd registered Contributor"
        # - label: "I'm Hacktoberfest registered Contributor"
