# .github/workflows/preview.yml
# name: Deploy PR previews

# on:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - closed

# concurrency: preview-${{ github.ref }}

# jobs:
#   deploy-preview:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Install and Build
#         if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed

#       - name: Deploy preview
#         uses: rossjrw/pr-preview-action@v1
#         with:
#           source-dir: ./build/

name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: |
          npm install

      - name: Build project
        if: github.event.action != 'closed'
        run: |
          npm run build

      - name: Deploy preview
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/

      - name: Cleanup preview (when PR is closed)
        if: github.event.action == 'closed'
        run: |
          echo "Cleaning up the preview environment for closed PR."
          